# Modify this configuration file directly when using the CLI, or via the menu on the left in the GUI app

[search]
device_family = "iphone_16_pro"     # the device family
models = ["MYM93LL/A", "MYMD3LL/A"] # the device types
carriers = ["UNLOCKED/US"]          # the carriers, if applicable
country_code = "us"                 # the country code
zip_code = "10153"                  # the zip-code area, can be left empty to use specific stores
stores = []                         # store-codes to search, can be left empty when using zip-code

[general]
polling_interval_seconds = 120 # recommended to make it > 10 seconds to account for processing time, make it > 30 when using random proxies
report_after_n_counts = 30     # after how many times a report should be generated
data_path = "data.csv"
log_path = "log.txt"
randomize_proxies = false

[telegram]
username = "azzbootycrack"                      # Your Telegram username (messages will be sent to this user)
api_id = "28111025"                        # Telegram bot API ID (usually an 8-digit number)
api_hash = "2c4a3dc759296992896fdfca60f7a256"                      # Telegram bot API hash
bot_token = "7856832966:AAGP1Tjin7e9-fqLg2KLw8af1phmOU5USpc"                     # Telegram bot token
session_name = "iPhone16ProFinder" # A unique name to create the virtual telegram client
